# 修复版 Dolphin SLAM 配置文件
# 统一话题命名，确保节点间正确通信

robot_state_node:
  ros__parameters:
    navigation_csv: "/media/psf/Samsung T7/SLAM Data/Sunboat_03-09-2023/2023-09-03-07-58-37/navigation/navigation.csv"
    base_frame: "base_link"
    odom_frame: "odom"
    map_frame: "map"
    publish_rate: 20.0
    publish_tf: true

image_processing_node:
  ros__parameters:
    camera_path: "/media/psf/Samsung T7/SLAM Data/Sunboat_03-09-2023/2023-09-03-07-58-37/camera"
    sonar_path: "/media/psf/Samsung T7/SLAM Data/Sunboat_03-09-2023/2023-09-03-07-58-37/sonar"
    feature_type: "SIFT"
    max_features: 500
    enable_visualization: true
    camera_topic: "/camera/image_raw"
    sonar_topic: "/sonar/image_raw"
    descriptors_topic: "/features/descriptors"
    keypoints_topic: "/features/keypoints"

local_view_node:
  ros__parameters:
    matching_algorithm: "fabmap"
    similarity_threshold: 0.65
    vocabulary_size: 500
    descriptors_topic: "/features/descriptors"
    matches_topic: "/local_view/matches"

place_cell_node:
  ros__parameters:
    neurons_per_dimension: 16
    update_rate: 20.0
    odometry_topic: "/dolphin_slam/odometry"    # 修正：统一使用dolphin_slam命名空间
    visual_match_topic: "/local_view/matches"
    activity_topic: "/place_cells/activity"

experience_map_node:
  ros__parameters:
    odometry_topic: "/dolphin_slam/odometry"    # 修正：统一使用dolphin_slam命名空间
    place_cell_topic: "/place_cells/activity"
    visual_match_topic: "/local_view/matches"
    match_threshold: 0.75
