
# 根据验证结果建议的配置：
robot_state_node:
  ros__parameters:
    navigation_csv: "/media/psf/Samsung T7/SLAM Data/Sunboat_03-09-2023/2023-09-03-07-58-37/navigation/navigation.csv"
    camera_csv: "/media/psf/Samsung T7/SLAM Data/Sunboat_03-09-2023/2023-09-03-07-58-37/camera.csv"
    sonar_csv: "/media/psf/Samsung T7/SLAM Data/Sunboat_03-09-2023/2023-09-03-07-58-37/sonar.csv"
    
image_processing_node:
  ros__parameters:
    camera_path: "/media/psf/Samsung T7/SLAM Data/Sunboat_03-09-2023/2023-09-03-07-58-37/camera"
    sonar_path: "/media/psf/Samsung T7/SLAM Data/Sunboat_03-09-2023/2023-09-03-07-58-37/sonar"
